version: '3'

services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db-game
      - SPRING_DATASOURCE_USERNAME=game
      - SPRING_DATASOURCE_PASSWORD=game@123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    networks:
      - app-network

  db:
    image: postgres:13.0-alpine
    container_name: db-game
    environment:
      - POSTGRES_USER=game
      - POSTGRES_PASSWORD=game@123
      - POSTGRES_DB=db-game
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
